### ISSUE TITLE
Error in mods.toml

### ISSUE THREAD

**Issue by GloriousGlider8** [RecraftorsMC/Enchantment-Decay#2]
In version Forge 1.20.1 (https://modrinth.com/mod/enchantment-decay/version/1.1), mods.toml contains an error (See Below)

```toml
modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU GPL 3.0"
issueTrackerURL="https://github.com/RecraftorsMC/enchantment_decay/issues"
[[mods]] #mandatory
modId="enchantment_decay" #mandatory
version="1.1.1" #mandatory
displayName="enchantment_decay" #mandatory
displayURL="https://github.com/RecraftorsMC/enchantment_decay"
logoFile="assets/icon.png" #optional
authors="Nerjal Nosk" #optional
displayTest="IGNORE_SERVER_VERSION"
description='''
Makes enchantments decay over use
'''
[[dependencies.enchantment_decay]] #optional
   modId="forge" #mandatory
   mandatory=true #mandatory
   versionRange="[47,)" #mandatory
   ordering="NONE"
   side="SERVER"
[[dependencies.enchantment_decay]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.20.1)"
   ordering="NONE"
   side="SERVER"
```

In dependencies.enchantment_decay (modid = minecraft), the version range is **[1.20.1)** and it should be **[1.20.1]**
